name: "Build Android SO"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
          unzip android-ndk-r27d-linux.zip
          echo "ANDROID_NDK=$PWD/android-ndk-r27d" >> $GITHUB_ENV

      - name: Build hev-socks5-tunnel
        run: $ANDROID_NDK/ndk-build APP_MODULES=hev-socks5-tunnel -j$(nproc)

      - name: Upload .so
        uses: actions/upload-artifact@v7
        with:
          name: hev-socks5-tunnel-so
          path: libs/*/libhev-socks5-tunnel.so
